version: '3.9'

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - php
      - mysql
    ports:
      - 81:80 # host:container
      - 444:443
    volumes:
    - ./wordpress:/var/www/html:delegated # host:container:mode
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql:delegated # host:container:mode
  php: 
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes: # volumes means that the files are shared between the host and the container
      - ./wordpress:/var/www/html:delegated # host:container:mode
  wp:
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    entrypoint: ['wp', '--allow-root']
    